//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shifttab
    {
        public int ID { get; set; }
        public System.DateTime date { get; set; }
        public string startshift { get; set; }
        public string endshift { get; set; }
    }
}
