//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertab
    {
        public int ID { get; set; }
        public string fullname { get; set; }
        public string username { get; set; }
        public int password { get; set; }
        public int numofaction { get; set; }
        public int dailyactions { get; set; }
    }
}
